---
- name: Install Greengrass V2

  hosts: all

  vars_prompt:
    - name: aws_access_key_id
      prompt: Enter your AWS_ACCESS_KEY_ID
      unsafe: yes
      private: no
    - name: aws_secret_access_key
      prompt: Enter your AWS_SECRET_ACCESS_KEY
      unsafe: yes
      private: yes
    - name: aws_region
      prompt: Enter your AWS region (i.e. us-east-1)
      private: no
    - name: greengrass_core_thing_name
      prompt: Enter a Thing name for your Greengrass Core
      private: no

  tasks:
    - name: Update repositories cache and install "openjdk-8-jdk" package
      become: yes
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes


    - name: Download the latest version of Greengrass Nucleus
      get_url:
        url: https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip
        dest: /home/pi/greengrass-nucleus-latest.zip

    - name: Create the Greengrass directory
      file:
        path: /home/pi/GreengrassCore
        state: directory

    - name: Unzip downloaded Greengrass Nucleus package
      unarchive:
        src: /home/pi/greengrass-nucleus-latest.zip
        dest: /home/pi/GreengrassCore
        remote_src: yes

    - name: Install Greengrass Nucleus
      register: install_results
      become: yes
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      shell: |
        java -Dlog.store=FILE \
          -jar ./GreengrassCore/lib/Greengrass.jar \
          --aws-region {{ aws_region }} \
          --root /greengrass/v2 \
          --thing-name {{ greengrass_core_thing_name }}GreengrassCore \
          --thing-group-name {{ greengrass_core_thing_name }}GreengrassCoreGroup \
          --tes-role-name GreengrassV2TokenExchangeRole \
          --tes-role-alias-name GreengrassTESCertificatePolicyGreengrassV2TokenExchangeRoleAlias \
          --component-default-user ggc_user:ggc_group \
          --provision true \
          --setup-system-service true \
          --deploy-dev-tools true

        chmod 755 /greengrass/v2 && chmod 755 /greengrass

    - debug: msg="{{install_results.stdout_lines}}"

    - name: Verify Status of Greengrass System service
      become: yes
      register: svcstatus
      command:
        cmd: systemctl status greengrass.service

    - debug: msg="{{svcstatus.stdout_lines}}"
